---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: "rkt.cert-manager-config"
    namespace: {{ .Values.argocd.namespace }}
spec:
    project: default
    source:
        chart: cert-manager-config
        repoURL: ghcr.io/riotkit-org/charts
        targetRevision: {{ .Values.certManager.version }}
        helm:
            values: ""

    destination:
        server: 'https://kubernetes.default.svc'
        namespace: {{ .Values.certManager.namespace }}
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
            - FailOnSharedResource=true
