---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: "rkt.nginx"
    namespace: {{ .Values.argocd.namespace }}
spec:
    project: default
    source:
        helm:
            releaseName: router
            values: |
                controller:
                    watchIngressWithoutClass: true
                    minReadySeconds: "10"
                    replicaCount: {{ .Values.nginx.replicas }}
                    autoscaling:
                        enabled: false
                        minReplicas: 1
                        maxReplicas: 2
                        targetCPUUtilizationPercentage: 50
                    {{ if .Values.nginx.enableMetrics }}
                    metrics:
                        enabled: true
                        serviceMonitor:
                            enabled: false
                            scrapeInterval: 2m
                    {{ end }}

                    {{ if .Values.nginx.onlyOnPrimary }}
                    #
                    # Run operator and gateway only on PRIMARY node
                    #
                    # REASONS:
                    #   1. Primary node is an entrypoint to the cluster
                    #   2. The incoming traffic should be predictable
                    #   3. Primary node is always TRUSTED. The incoming traffic must be protected for privacy of the users and admins
                    #
                    nodeSelector:
                        node-type: primary
                    {{ else }}
                    nodeSelector:
                        is-router: yes
                    {{ end }}
                    tolerations:
                        - key: "node-role.kubernetes.io/master"
                          operator: "Exists"
                          effect: "NoSchedule"
                    resources:
                        {{ toYaml .Values.nginx.resources }}
                    readinessProbe:
                        initialDelaySeconds: 20
                        periodSeconds: 45
                        failureThreshold: 2
                    livenessProbe:
                        initialDelaySeconds: 20
                        periodSeconds: 55
                        failureThreshold: 1
                    service:
                        externalTrafficPolicy: Local
                    config:
                        {{ if .Values.nginx.enableModSecurity }}
                        enable-modsecurity: "true"
                        enable-owasp-modsecurity-crs: "true"
                        modsecurity-snippet: |
                            SecRuleEngine On
                        {{ end }}
                        disable-access-log: "true"
                        disable-ipv6: "true"

        targetRevision: {{ .Values.nginx.version }}
        chart: ingress-nginx
        repoURL: https://kubernetes.github.io/ingress-nginx
    destination:
        server: https://kubernetes.default.svc
        namespace: {{ .Values.nginx.namespace }}
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
            - FailOnSharedResource=true
